<?php

declare(strict_types=1);

use App\Http\Controllers\AssetController;
use App\Http\Controllers\AuditController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ApiDocsController;
use App\Http\Controllers\ApiController;
use App\Http\Controllers\AdministrativeFormController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LicenseController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PreferenceController;
use App\Http\Controllers\RequestController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SparePartController;
use App\Http\Controllers\StorageController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\ToolsController;
use App\Http\Controllers\UserController;
use App\Support\Router;

return static function (Router $router): void {
    $router->get('/login', [AuthController::class, 'showLogin'], 'login');
    $router->post('/login', [AuthController::class, 'login'], 'login.attempt');
    $router->post('/logout', [AuthController::class, 'logout'], 'logout');
    $router->get('/locale/{locale}', [PreferenceController::class, 'locale'], 'locale.switch');
    $router->post('/theme/toggle', [PreferenceController::class, 'theme'], 'theme.toggle');
    $router->post('/notifications/read-all', [NotificationController::class, 'readAll'], 'notifications.read_all');
    $router->get('/', [DashboardController::class, 'index'], 'dashboard');
    $router->get('/api/docs', [ApiDocsController::class, 'index'], 'api.docs');
    $router->get('/api/openapi.json', [ApiDocsController::class, 'spec'], 'api.spec');
    $router->get('/api/v1/dashboard', [ApiController::class, 'dashboard'], 'api.dashboard');
    $router->get('/api/v1/assets', [ApiController::class, 'assets'], 'api.assets');
    $router->get('/api/v1/assets/{id}', [ApiController::class, 'asset'], 'api.assets.show');
    $router->get('/api/v1/branches', [ApiController::class, 'branches'], 'api.branches');
    $router->get('/api/v1/branches/{id}', [ApiController::class, 'branch'], 'api.branches.show');
    $router->get('/api/v1/categories', [ApiController::class, 'categories'], 'api.categories');
    $router->get('/api/v1/employees', [ApiController::class, 'employees'], 'api.employees');
    $router->get('/api/v1/employees/{id}', [ApiController::class, 'employee'], 'api.employees.show');
    $router->get('/api/v1/licenses', [ApiController::class, 'licenses'], 'api.licenses');
    $router->get('/api/v1/licenses/{id}', [ApiController::class, 'license'], 'api.licenses.show');
    $router->get('/api/v1/spare-parts', [ApiController::class, 'spareParts'], 'api.spare_parts');
    $router->get('/api/v1/reports/summary', [ApiController::class, 'reports'], 'api.reports');
    $router->resource('requests', RequestController::class);
    $router->post('/requests/{id}/submit', [RequestController::class, 'submit'], 'requests.submit');
    $router->post('/requests/{id}/decision', [RequestController::class, 'decision'], 'requests.decision');
    $router->post('/requests/{id}/fulfill-storage', [RequestController::class, 'fulfillStorage'], 'requests.fulfill_storage');
    $router->post('/requests/{id}/link-existing-assets', [RequestController::class, 'linkExistingAssets'], 'requests.link_existing_assets');
    $router->post('/requests/{id}/advance', [RequestController::class, 'advance'], 'requests.advance');
    $router->get('/assets/archived', [AssetController::class, 'archived'], 'assets.archived');
    $router->get('/assets/export', [AssetController::class, 'export'], 'assets.export');
    $router->post('/assets/bulk-action', [AssetController::class, 'bulkAction'], 'assets.bulk');
    $router->resource('assets', AssetController::class);
    $router->get('/assets/{id}/move', [AssetController::class, 'moveForm'], 'assets.move');
    $router->post('/assets/{id}/move', [AssetController::class, 'moveStore'], 'assets.move.store');
    $router->get('/assets/{id}/return', [AssetController::class, 'returnForm'], 'assets.return');
    $router->post('/assets/{id}/return', [AssetController::class, 'returnStore'], 'assets.return.store');
    $router->get('/assets/{id}/repair', [AssetController::class, 'repairForm'], 'assets.repair');
    $router->post('/assets/{id}/repair', [AssetController::class, 'repairStore'], 'assets.repair.store');
    $router->get('/assets/{id}/archive', [AssetController::class, 'archiveForm'], 'assets.archive');
    $router->post('/assets/{id}/archive', [AssetController::class, 'archiveStore'], 'assets.archive.store');
    $router->get('/assets/{id}/handover', [AssetController::class, 'handoverForm'], 'assets.handover');
    $router->post('/assets/{id}/handover', [AssetController::class, 'handoverStore'], 'assets.handover.store');
    $router->get('/handovers/{id}/print', [AssetController::class, 'handoverPrint'], 'assets.handover.print');
    $router->get('/assets/{id}/maintenance', [AssetController::class, 'maintenanceForm'], 'assets.maintenance');
    $router->post('/assets/{id}/maintenance', [AssetController::class, 'maintenanceStore'], 'assets.maintenance.store');
    $router->resource('branches', BranchController::class);
    $router->get('/storage', [StorageController::class, 'index'], 'storage.index');
    $router->get('/storage/export', [StorageController::class, 'export'], 'storage.export');
    $router->resource('categories', CategoryController::class);
    $router->resource('employees', EmployeeController::class);
    $router->get('/employees/{id}/offboarding', [EmployeeController::class, 'offboardingForm'], 'employees.offboarding');
    $router->post('/employees/{id}/offboarding', [EmployeeController::class, 'offboardingStore'], 'employees.offboarding.store');
    $router->resource('licenses', LicenseController::class);
    $router->post('/licenses/{id}/renew', [LicenseController::class, 'renew'], 'licenses.renew');
    $router->resource('spare-parts', SparePartController::class);
    $router->get('/reports', [ReportController::class, 'index'], 'reports.index');
    $router->get('/reports/export', [ReportController::class, 'export'], 'reports.export');
    $router->get('/administrative-forms', [AdministrativeFormController::class, 'index'], 'administrative-forms.index');
    $router->get('/administrative-forms/create', [AdministrativeFormController::class, 'create'], 'administrative-forms.create');
    $router->post('/administrative-forms', [AdministrativeFormController::class, 'store'], 'administrative-forms.store');
    $router->get('/administrative-forms/{id}/edit', [AdministrativeFormController::class, 'edit'], 'administrative-forms.edit');
    $router->put('/administrative-forms/{id}', [AdministrativeFormController::class, 'update'], 'administrative-forms.update');
    $router->delete('/administrative-forms/{id}', [AdministrativeFormController::class, 'destroy'], 'administrative-forms.destroy');
    $router->get('/administrative-forms/{id}', [AdministrativeFormController::class, 'show'], 'administrative-forms.show');
    $router->get('/administrative-forms/{id}/download/{variant}', [AdministrativeFormController::class, 'download'], 'administrative-forms.download');
    $router->get('/audit-logs', [AuditController::class, 'index'], 'audit.index');
    $router->get('/audit-logs/export', [AuditController::class, 'export'], 'audit.export');
    $router->resource('users', UserController::class);
    $router->get('/settings', [SystemController::class, 'settings'], 'settings');
    $router->post('/settings/general', [SystemController::class, 'saveGeneral'], 'settings.general.save');
    $router->post('/settings/auth', [SystemController::class, 'saveAuth'], 'settings.auth.save');
    $router->post('/settings/security', [SystemController::class, 'saveSecurity'], 'settings.security.save');
    $router->post('/settings/permissions', [SystemController::class, 'savePermissions'], 'settings.permissions.save');
    $router->post('/settings/backups/create', [SystemController::class, 'createBackup'], 'settings.backups.create');
    $router->get('/tools/import-export', [ToolsController::class, 'index'], 'tools.index');
    $router->get('/tools/import-export/{dataset}/export', [ToolsController::class, 'export'], 'tools.export');
    $router->get('/tools/import-export/{dataset}/template', [ToolsController::class, 'template'], 'tools.template');
    $router->post('/tools/import-export/{dataset}/import', [ToolsController::class, 'import'], 'tools.import');
    $router->get('/system-check', [SystemController::class, 'check'], 'system.check');
};
